version: '3.3'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  adminer:
    depends_on:
      - db
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    depends_on:
      - db
    image: node
    container_name: server
    volumes:
      - ./:/app
    working_dir: /app
    command: ["sh", "-c", "npx prisma db pull && npx prisma generate && yarn && yarn start:dev"]
    restart: always
    ports:
      - 5000:5000

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none' 
      o: bind
      device: $PWD/database/data