version: '3.3'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    env_file:
      - .env

  adminer:
    depends_on:
      - db
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  
  server:
    depends_on:
      - db
    build: ./
    image: server
    container_name: server
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/app